popis = (  
( "minecraft:cobblestone" , "0") , 
( "minecraft:dirt" , "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sandstone" ,  "0" ) ,
( "minecraft:stone" ,  "0" ) ,
( "minecraft:stone" ,  "1" ) ,  #### GRANITE
( "minecraft:stone" , "3" ) , #Diorite
( "minecraft:stone" , "5" ) , #Andesite
( "minecraft:coal" , "0") ,
( "minecraft:flint" , "0") ,
( "minecraft:iron_ore" , "0") ,
( "minecraft:gold_ore" , "0") ,
( "minecraft:redstone" , "0") ,
( "minecraft:redstone_block" , "0") ,
( "minecraft:stonebrick" , "0") ,
( "minecraft:log" , "0") , #oak wood
( "minecraft:planks" , "0") , #Oak Wood Planks
( "minecraft:stick" , "0") , 
( "minecraft:torch" , "0") ,
( "minecraft:wheat" , "0" ) ,
( "minecraft:clay_ball" , "0") ,
( "minecraft:clay" , "0") ,
( "minecraft:obsidian" , "0") ,
( "minecraft:glowstone" , "0") ,
( "minecraft:stone_brick_stairs" , "0") ,
( "minecraft:sandstone_stairs" , "0") ,
( "minecraft:brick" , "0") ,
( "minecraft:glass" , "0") ,
( "minecraft:glass_pane" , "0") ,
( "minecraft:log" , "1") , #spurce wood
( "minecraft:planks" , "0") , #Spruce Wood Planks
( "minecraft:oak_stairs" , "0") , 
( "minecraft:spruce_stairs" , "0") , 
( "minecraft:redstone_torch" , "0") ,
( "minecraft:chest" , "0") ,
( "minecraft:dye" , "4") , #Lapis Lazuli
( "minecraft:diamond" , "0") ,
( "minecraft:emerald" , "0") ,
( "minecraft:iron_ingot" , "0") ,
( "minecraft:iron_ingot" , "0") ,
( "minecraft:gold_ingot" , "0") ,
( "minecraft:bone" , "0" ) ,
( "minecraft:string" , "0" ) ,
( "minecraft:feather" , "0" ) ,
( "minecraft:wool" , "0" ) , #whote wool
( "minecraft:chicken" , "0" ) ,
( "minecraft:porkchop" , "0" ) ,
( "minecraft:beef" , "0" ) ,
( "minecraft:leather" , "0" ) ,
( "minecraft:vine" , "0") , 
( "minecraft:cactus" , "0" ) ,
( "minecraft:bread" , "0" ) ,
( "minecraft:apple" , "0" ) ,
( "minecraft:pumpkin" , "0" ) ,
( "minecraft:melon" , "0" ) ,
( "minecraft:carrot" , "0" ) ,
( "minecraft:potato" , "0" ) ,
( "minecraft:reeds" , "0" ) ,
( "minecraft:red_mushroom" , "0" ) ,
( "minecraft:brown_mushroom" , "0" ) ,
( "minecraft:wheat_seeds" , "0" ) ,
( "minecraft:pumpkin_seeds" , "0" ) ,
( "minecraft:melon_seeds" , "0" ) ,
( "minecraft:dye" , "3" ) ,   #cocoa seeds
( "minecraft:sapling" , "0" ) , #Oak sapling
( "minecraft:sapling" , "1" ) , #Spruce sapling
( "minecraft:sapling" , "2" ) , #Birch  sapling
( "minecraft:sapling" , "3" ) , #Jungle sapling
( "minecraft:sapling" , "4" ) , #Acacia sapling
( "minecraft:sapling" , "5" ) , #Dark Oak  sapling
( "minecraft:ladder" , "0" ) ,
( "minecraft:rail" , "0" ) ,
( "minecraft:golden_rail" , "0" ) ,
( "minecraft:detector_rail" , "0" ) ,
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:dirt" , "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:gravel" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:sand" ,  "0" ) ,
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
( "minecraft:cobblestone" , "0") , 
)

def materialGenerator2 ():
   for br in popis:
      yield br

def materialGenerator ():
   while 1 == 1:
      yield ( "minecraft:item_frame" , "0")    # item_frame - pocetno punjenje
